# Generated by Django 4.1.1 on 2023-01-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bid', models.DecimalField(decimal_places=1, max_digits=15)),
                ('closed', models.BooleanField(default=False)),
            ],
        )
    ]
