# Generated by Django 4.1.1 on 2023-01-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granola_shop', '0003_checkoutaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
    ]
