# Generated by Django 4.1.1 on 2023-01-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granola_shop', '0004_remove_order_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='apartment_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
