# Generated by Django 4.1.1 on 2023-01-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granola_shop', '0005_alter_checkoutaddress_apartment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='first_name',
            field=models.CharField(default='Nata', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='last_name',
            field=models.CharField(default='Nata', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='street_address',
            field=models.CharField(max_length=255),
        ),
    ]
