# Generated by Django 4.1.1 on 2023-01-23 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granola_shop', '0007_alter_checkoutaddress_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='granola_shop.checkoutaddress'),
        ),
    ]
