# Generated by Django 4.1.1 on 2023-01-23 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granola_shop', '0008_order_checkout_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the following format: 0501234567', regex='^(05)\\d{8}$')]),
        ),
    ]
